# SonarQube Metrics Dashboard

title: "SonarQube Metrics Dashboard"
description: "Real-time code quality insights across all projects"
url: "https://diogo-a-rocha-alb.github.io"
baseurl: ""

# Jekyll settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github/
  - docs/

# Custom variables
dashboard:
  refresh_interval: 300000  # 5 minutes in milliseconds